---

kde_config_files:
  - plasma-org.kde.plasma.desktop-appletsrc
  - plasmashellrc
  - kwinrc
  - kdeglobals
  - plasmarc
  - kscreenlockerrc
  - kcminputrc
  - kglobalshortcutsrc
  - kxkbrc                    # keyboard layout
  - breezerc                  # Breeze theme settings
  - khotkeysrc                # custom hotkeys
  - powermanagementprofilesrc # power profiles
  - ksmserverrc               # session manager

kde_config_dirs:
  - gtk-3.0                   # GTK3 theme integration
  - gtk-4.0                   # GTK4 theme integration

kde_local_dirs:
  - plasma/plasmoids          # custom widgets
  - color-schemes
  - aurorae/themes            # window decorations
  - wallpapers
  - konsole
  - kwin/scripts              # KWin scripts
  - kwin/effects              # custom effects