---

- name: Configure New Kubuntu install via Ansible Pull
  hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  roles:
    #- createNewUser
    - hardenSystem
    #- kdeCustomisation
    #- installApps